version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./index.html:/usr/share/nginx/html/index.htmL