version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
